import { createFileRoute } from "@tanstack/react-router";
import { StaticPage } from "@/components/site/StaticPage";
import { useApp } from "@/lib/providers";

const UPDATED = "July 30, 2026";
const UPDATED_PT = "30 de julho de 2026";

const content = {
  en: {
    eyebrow: "Legal",
    title: "Privacy Policy",
    subtitle: `Last updated: ${UPDATED}`,
    sections: [
      {
        title: "1. Who We Are",
        body: "Branchly is a reputation intelligence platform operated by Branchly Tecnologia Ltda., headquartered in Brazil. We provide review monitoring, competitive benchmarking and AI-powered insights for local and multi-location businesses. References to 'Branchly', 'we', 'us' or 'our' in this policy refer to that entity.",
      },
      {
        title: "2. Information We Collect",
        body: "We collect information you provide directly (name, email, business details, billing information), information generated by your use of the service (connected Google Business Profile data, reviews captured via integrations, attribution events from the Branchly pixel, WhatsApp message metadata) and information collected automatically (IP address, browser type, pages visited, session duration). We do not sell your personal data.",
      },
      {
        title: "3. How We Use Your Information",
        body: "We use your information to provide and improve the service, send you product updates and transactional emails, respond to support requests, detect and prevent fraud, comply with legal obligations and generate aggregate analytics. We do not use your data to train third-party AI models without your explicit consent.",
      },
      {
        title: "4. Data Sharing",
        body: "We share your information with service providers who help us operate Branchly (hosting, email, analytics, payment processing) under strict data processing agreements. We may share data when required by law. We do not sell, rent or share your personal information with third parties for their own marketing purposes.",
      },
      {
        title: "5. Data Retention",
        body: "We retain your data for as long as your account is active. When you delete your account, we remove personal data within 30 days, except where retention is required by law or for legitimate business purposes (e.g., resolving disputes, preventing fraud).",
      },
      {
        title: "6. Your Rights",
        body: "Depending on your location, you may have rights to access, correct, delete or port your personal data, and to withdraw consent or object to certain processing. To exercise these rights, contact privacy@branchly.com.br. We will respond within 30 days.",
      },
      {
        title: "7. Cookies",
        body: "We use essential cookies for authentication and session management, and optional analytics cookies to understand how users interact with the product. You can disable non-essential cookies in your browser settings. Our attribution pixel uses first-party storage only.",
      },
      {
        title: "8. Security",
        body: "We protect your data with encryption in transit (TLS 1.2+) and at rest, access controls limiting data access to authorized personnel, regular security reviews and monitoring. See our Security page for more details.",
      },
      {
        title: "9. Children",
        body: "Branchly is not directed to children under 16. We do not knowingly collect personal information from children. If you believe we have collected such information, contact us immediately.",
      },
      {
        title: "10. Changes to This Policy",
        body: "We may update this policy from time to time. We will notify you of material changes by email or in-product notice at least 30 days before they take effect. Continued use after the effective date constitutes acceptance.",
      },
      {
        title: "11. Contact",
        body: "Questions about this policy: privacy@branchly.com.br | Branchly Tecnologia Ltda., Brazil.",
      },
    ],
  },
  pt: {
    eyebrow: "Legal",
    title: "Política de Privacidade",
    subtitle: `Última atualização: ${UPDATED_PT}`,
    sections: [
      {
        title: "1. Quem Somos",
        body: "O Branchly é uma plataforma de inteligência de reputação operada pela Branchly Tecnologia Ltda., sediada no Brasil. Fornecemos monitoramento de avaliações, benchmarking competitivo e insights com IA para negócios locais e multi-unidade. Referências a 'Branchly', 'nós' ou 'nosso' nesta política se referem a essa entidade.",
      },
      {
        title: "2. Informações que Coletamos",
        body: "Coletamos informações que você fornece diretamente (nome, e-mail, dados do negócio, informações de pagamento), informações geradas pelo uso do serviço (dados do Google Meu Negócio conectado, avaliações capturadas pelas integrações, eventos de atribuição do pixel do Branchly, metadados de mensagens do WhatsApp) e informações coletadas automaticamente (endereço IP, tipo de navegador, páginas visitadas, duração da sessão). Não vendemos seus dados pessoais.",
      },
      {
        title: "3. Como Usamos suas Informações",
        body: "Usamos suas informações para fornecer e melhorar o serviço, enviar atualizações de produto e e-mails transacionais, responder a solicitações de suporte, detectar e prevenir fraudes, cumprir obrigações legais e gerar análises agregadas. Não usamos seus dados para treinar modelos de IA de terceiros sem seu consentimento explícito.",
      },
      {
        title: "4. Compartilhamento de Dados",
        body: "Compartilhamos suas informações com prestadores de serviço que nos ajudam a operar o Branchly (hospedagem, e-mail, analytics, processamento de pagamentos) sob rigorosos acordos de processamento de dados. Podemos compartilhar dados quando exigido por lei. Não vendemos, alugamos nem compartilhamos seus dados pessoais com terceiros para fins de marketing próprio.",
      },
      {
        title: "5. Retenção de Dados",
        body: "Retemos seus dados pelo tempo em que sua conta estiver ativa. Quando você excluir sua conta, removeremos os dados pessoais em até 30 dias, exceto quando a retenção for exigida por lei ou para fins legítimos de negócio (ex.: resolução de disputas, prevenção de fraudes).",
      },
      {
        title: "6. Seus Direitos",
        body: "Dependendo de sua localização, você pode ter direitos de acesso, correção, exclusão ou portabilidade de seus dados pessoais, além de retirar consentimento ou contestar determinados tratamentos. Para exercer esses direitos, entre em contato em privacy@branchly.com.br. Responderemos em até 30 dias.",
      },
      {
        title: "7. Cookies",
        body: "Usamos cookies essenciais para autenticação e gestão de sessão, e cookies de analytics opcionais para entender como os usuários interagem com o produto. Você pode desativar cookies não essenciais nas configurações do navegador. Nosso pixel de atribuição usa apenas armazenamento próprio (first-party).",
      },
      {
        title: "8. Segurança",
        body: "Protegemos seus dados com criptografia em trânsito (TLS 1.2+) e em repouso, controles de acesso limitando o acesso a dados a pessoal autorizado, revisões e monitoramento regulares de segurança. Consulte nossa página de Segurança para mais detalhes.",
      },
      {
        title: "9. Crianças",
        body: "O Branchly não é direcionado a crianças menores de 16 anos. Não coletamos intencionalmente informações pessoais de crianças. Se acreditar que coletamos tais informações, entre em contato imediatamente.",
      },
      {
        title: "10. Alterações nesta Política",
        body: "Podemos atualizar esta política periodicamente. Notificaremos sobre mudanças materiais por e-mail ou aviso no produto com pelo menos 30 dias de antecedência. O uso continuado após a data de vigência constitui aceitação.",
      },
      {
        title: "11. Contato",
        body: "Dúvidas sobre esta política: privacy@branchly.com.br | Branchly Tecnologia Ltda., Brasil.",
      },
    ],
  },
};

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Branchly" },
      { name: "description", content: "Branchly privacy policy: how we collect, use and protect your personal data." },
    ],
    links: [{ rel: "canonical", href: "https://branchly.com.br/privacy" }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { locale } = useApp();
  const c = content[locale];

  return (
    <StaticPage eyebrow={c.eyebrow} title={c.title} subtitle={c.subtitle}>
      <div className="rounded-xl border border-border bg-card divide-y divide-border">
        {c.sections.map((s) => (
          <div key={s.title} className="px-6 py-6 md:px-8">
            <h2 className="font-semibold text-foreground mb-2">{s.title}</h2>
            <p className="text-sm leading-relaxed text-muted-foreground">{s.body}</p>
          </div>
        ))}
      </div>
    </StaticPage>
  );
}
