/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as GuiaAparecerNasPrimeirasPaginasDoGoogleRouteImport } from './routes/guia.aparecer-nas-primeiras-paginas-do-google'
import { Route as GuiaMelhorarReputacaoNoGoogleRouteImport } from './routes/guia.melhorar-reputacao-no-google'
import { Route as GuideImproveGoogleReputationRouteImport } from './routes/guide.improve-google-reputation'
import { Route as GuideRankFirstPageGoogleRouteImport } from './routes/guide.rank-first-page-google'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedAdminFinancialRouteImport } from './routes/_authenticated/admin/financial'
import { Route as AuthenticatedAdminGeoRouteImport } from './routes/_authenticated/admin/geo'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated/admin/insights'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin/seo'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as IntegrationsFacebookCallbackRouteImport } from './routes/integrations.facebook.callback'
import { Route as ApiCollectRouteImport } from './routes/api.collect'
import { Route as ApiPixelPixelIdRouteImport } from './routes/api.pixel.$pixelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GuiaAparecerNasPrimeirasPaginasDoGoogleRoute =
  GuiaAparecerNasPrimeirasPaginasDoGoogleRouteImport.update({
    id: '/guia/aparecer-nas-primeiras-paginas-do-google',
    path: '/guia/aparecer-nas-primeiras-paginas-do-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaMelhorarReputacaoNoGoogleRoute =
  GuiaMelhorarReputacaoNoGoogleRouteImport.update({
    id: '/guia/melhorar-reputacao-no-google',
    path: '/guia/melhorar-reputacao-no-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuideImproveGoogleReputationRoute =
  GuideImproveGoogleReputationRouteImport.update({
    id: '/guide/improve-google-reputation',
    path: '/guide/improve-google-reputation',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuideRankFirstPageGoogleRoute =
  GuideRankFirstPageGoogleRouteImport.update({
    id: '/guide/rank-first-page-google',
    path: '/guide/rank-first-page-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancialRoute =
  AuthenticatedAdminFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGeoRoute = AuthenticatedAdminGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const IntegrationsFacebookCallbackRoute =
  IntegrationsFacebookCallbackRouteImport.update({
    id: '/integrations/facebook/callback',
    path: '/integrations/facebook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCollectRoute = ApiCollectRouteImport.update({
  id: '/api/collect',
  path: '/api/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPixelPixelIdRoute = ApiPixelPixelIdRouteImport.update({
  id: '/api/pixel/$pixelId',
  path: '/api/pixel/$pixelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/pixel/$pixelId': typeof ApiPixelPixelIdRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia/aparecer-nas-primeiras-paginas-do-google': typeof GuiaAparecerNasPrimeirasPaginasDoGoogleRoute
  '/guia/melhorar-reputacao-no-google': typeof GuiaMelhorarReputacaoNoGoogleRoute
  '/guide/improve-google-reputation': typeof GuideImproveGoogleReputationRoute
  '/guide/rank-first-page-google': typeof GuideRankFirstPageGoogleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/integrations/facebook/callback': typeof IntegrationsFacebookCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/pixel/$pixelId': typeof ApiPixelPixelIdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia/aparecer-nas-primeiras-paginas-do-google': typeof GuiaAparecerNasPrimeirasPaginasDoGoogleRoute
  '/guia/melhorar-reputacao-no-google': typeof GuiaMelhorarReputacaoNoGoogleRoute
  '/guide/improve-google-reputation': typeof GuideImproveGoogleReputationRoute
  '/guide/rank-first-page-google': typeof GuideRankFirstPageGoogleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/integrations/facebook/callback': typeof IntegrationsFacebookCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/collect': typeof ApiCollectRoute
  '/api/pixel/$pixelId': typeof ApiPixelPixelIdRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/guia/aparecer-nas-primeiras-paginas-do-google': typeof GuiaAparecerNasPrimeirasPaginasDoGoogleRoute
  '/guia/melhorar-reputacao-no-google': typeof GuiaMelhorarReputacaoNoGoogleRoute
  '/guide/improve-google-reputation': typeof GuideImproveGoogleReputationRoute
  '/guide/rank-first-page-google': typeof GuideRankFirstPageGoogleRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/_authenticated/admin/geo': typeof AuthenticatedAdminGeoRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/integrations/facebook/callback': typeof IntegrationsFacebookCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/collect'
    | '/api/pixel/$pixelId'
    | '/admin'
    | '/dashboard'
    | '/guia/aparecer-nas-primeiras-paginas-do-google'
    | '/guia/melhorar-reputacao-no-google'
    | '/guide/improve-google-reputation'
    | '/guide/rank-first-page-google'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/ai'
    | '/admin/branding'
    | '/admin/financial'
    | '/admin/geo'
    | '/admin/insights'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/seo'
    | '/admin/users'
    | '/integrations/facebook/callback'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/collect'
    | '/api/pixel/$pixelId'
    | '/dashboard'
    | '/guia/aparecer-nas-primeiras-paginas-do-google'
    | '/guia/melhorar-reputacao-no-google'
    | '/guide/improve-google-reputation'
    | '/guide/rank-first-page-google'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/ai'
    | '/admin/branding'
    | '/admin/financial'
    | '/admin/geo'
    | '/admin/insights'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/seo'
    | '/admin/users'
    | '/integrations/facebook/callback'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/guia/aparecer-nas-primeiras-paginas-do-google'
    | '/guia/melhorar-reputacao-no-google'
    | '/guide/improve-google-reputation'
    | '/guide/rank-first-page-google'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/financial'
    | '/_authenticated/admin/geo'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/users'
    | '/integrations/facebook/callback'
    | '/_authenticated/admin/'
    | '/api/collect'
    | '/api/pixel/$pixelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCollectRoute: typeof ApiCollectRoute
  ApiPixelPixelIdRoute: typeof ApiPixelPixelIdRoute
  GuiaAparecerNasPrimeirasPaginasDoGoogleRoute: typeof GuiaAparecerNasPrimeirasPaginasDoGoogleRoute
  GuiaMelhorarReputacaoNoGoogleRoute: typeof GuiaMelhorarReputacaoNoGoogleRoute
  GuideImproveGoogleReputationRoute: typeof GuideImproveGoogleReputationRoute
  GuideRankFirstPageGoogleRoute: typeof GuideRankFirstPageGoogleRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  IntegrationsFacebookCallbackRoute: typeof IntegrationsFacebookCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collect': {
      id: '/api/collect'
      path: '/api/collect'
      fullPath: '/api/collect'
      preLoaderRoute: typeof ApiCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pixel/$pixelId': {
      id: '/api/pixel/$pixelId'
      path: '/api/pixel/$pixelId'
      fullPath: '/api/pixel/$pixelId'
      preLoaderRoute: typeof ApiPixelPixelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/guia/aparecer-nas-primeiras-paginas-do-google': {
      id: '/guia/aparecer-nas-primeiras-paginas-do-google'
      path: '/guia/aparecer-nas-primeiras-paginas-do-google'
      fullPath: '/guia/aparecer-nas-primeiras-paginas-do-google'
      preLoaderRoute: typeof GuiaAparecerNasPrimeirasPaginasDoGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/melhorar-reputacao-no-google': {
      id: '/guia/melhorar-reputacao-no-google'
      path: '/guia/melhorar-reputacao-no-google'
      fullPath: '/guia/melhorar-reputacao-no-google'
      preLoaderRoute: typeof GuiaMelhorarReputacaoNoGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/improve-google-reputation': {
      id: '/guide/improve-google-reputation'
      path: '/guide/improve-google-reputation'
      fullPath: '/guide/improve-google-reputation'
      preLoaderRoute: typeof GuideImproveGoogleReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/rank-first-page-google': {
      id: '/guide/rank-first-page-google'
      path: '/guide/rank-first-page-google'
      fullPath: '/guide/rank-first-page-google'
      preLoaderRoute: typeof GuideRankFirstPageGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financial': {
      id: '/_authenticated/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AuthenticatedAdminFinancialRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/geo': {
      id: '/_authenticated/admin/geo'
      path: '/geo'
      fullPath: '/admin/geo'
      preLoaderRoute: typeof AuthenticatedAdminGeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/integrations/facebook/callback': {
      id: '/integrations/facebook/callback'
      path: '/integrations/facebook/callback'
      fullPath: '/integrations/facebook/callback'
      preLoaderRoute: typeof IntegrationsFacebookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminFinancialRoute: typeof AuthenticatedAdminFinancialRoute
  AuthenticatedAdminGeoRoute: typeof AuthenticatedAdminGeoRoute
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
    AuthenticatedAdminFinancialRoute: AuthenticatedAdminFinancialRoute,
    AuthenticatedAdminGeoRoute: AuthenticatedAdminGeoRoute,
    AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCollectRoute: ApiCollectRoute,
  ApiPixelPixelIdRoute: ApiPixelPixelIdRoute,
  GuiaAparecerNasPrimeirasPaginasDoGoogleRoute:
    GuiaAparecerNasPrimeirasPaginasDoGoogleRoute,
  GuiaMelhorarReputacaoNoGoogleRoute: GuiaMelhorarReputacaoNoGoogleRoute,
  GuideImproveGoogleReputationRoute: GuideImproveGoogleReputationRoute,
  GuideRankFirstPageGoogleRoute: GuideRankFirstPageGoogleRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  IntegrationsFacebookCallbackRoute: IntegrationsFacebookCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
